set_global_assignment -name VHDL_FILE rtl/snn_pkg.vhd
set_global_assignment -name VHDL_FILE rtl/network_params_pkg.vhd
set_global_assignment -name VHDL_FILE rtl/neuron_params_pkg.vhd
set_global_assignment -name VHDL_FILE rtl/synapse_params_pkg.vhd
set_global_assignment -name VHDL_FILE rtl/trace_data_pkg.vhd
set_global_assignment -name VHDL_FILE rtl/trace_rom.vhd
set_global_assignment -name VHDL_FILE rtl/addr_counter.vhd
set_global_assignment -name VHDL_FILE rtl/inference_counter.vhd
set_global_assignment -name VHDL_FILE rtl/input_buffer.vhd
set_global_assignment -name VHDL_FILE rtl/lif_neuron.vhd
set_global_assignment -name VHDL_FILE rtl/synapse_accumulator.vhd
set_global_assignment -name VHDL_FILE rtl/neuron_bank.vhd
set_global_assignment -name VHDL_FILE rtl/snn_core.vhd
set_global_assignment -name VHDL_FILE rtl/output_register.vhd
set_global_assignment -name VHDL_FILE rtl/wta.vhd
set_global_assignment -name VHDL_FILE rtl/controller_fsm.vhd
set_global_assignment -name VHDL_FILE rtl/datapath.vhd
set_global_assignment -name VHDL_FILE rtl/neuromorphic_sca_top.vhd
